### ISSUE TITLE
[Bug]  Replace Image Registry Deployment and Pod level replacement overlap 

### ISSUE THREAD

**Issue by abelnieva** [kyverno/policies#347]
### Kyverno Version

1.6.x

### Kubernetes Version

1.21.x

### Kubernetes Platform

EKS

### Description

We are facing the following issues with [replace image policy](https://kyverno.io/policies/other/replace_image_registry/replace_image_registry/) 

as soon as you create the policy it works well when you terminate a POD. The problem starts when you rollout a deployment, the policy also update the image uri at deployment level. then it run the REGEX regex_replace_all('^[^/]+',... but against the image who was already updated the registry so fail 

In short: Policy would work if you dont rollout anything 

### Steps to reproduce

1. Setup Policy [Replace Image Registry](https://kyverno.io/policies/other/replace_image_registry/replace_image_registry/)  
Registry to add 4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io
2. Terminating  a pod works well 
3. Roll out a deployment. The deployment image would change to  4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io/rancher/agent:XXX
4. Terminate a pod in the deployment
 Pod image is  4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io/**mirror/docker.io**/rancher/agent:XXX
now we got mirror/docker.io twice 

WE ONLY SEE THIS ISSUE ROLLING OUT THE DEPLOYMENT 

### Expected behavior

After rollout the deployment the either at deployment level and pod level the value should be 

Before 
rancher/agent:XXX

After
4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io/rancher/agent:XXX 

### Screenshots

![image](https://user-images.githubusercontent.com/12033455/174058315-9485a33e-9eaa-42aa-8c85-0cb45f6428cd.png)

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hi @abelnieva and sorry for the delay and the issue. I will push an update to this policy which should fix the issue. Here is the updated policy which requires Kyverno 1.6.0+. Can you confirm this fixes it for you?

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Rather than blocking Pods which come from outside registries,
      it is also possible to mutate them so the pulls are directed to
      approved registries. In some cases, those registries may function as
      pull-through proxies and can fetch the image if not cached.
      This policy policy mutates all images either
      in the form 'image:tag' or 'registry.corp.com/image:tag' to be 
      `myregistry.corp.com/`. Any path in the image name will be preserved.      
spec:
  background: false
  rules:
    - name: replace-image-registry-pod-containers
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', 'myregistry.corp.com' )}}"
    - name: replace-image-registry-pod-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', 'myregistry.corp.com' )}}"
```

**Comment by chipzoller** [comment]
cc @devopsrick @pparth @ymitsos @jjungnickel @muhammad-hassan-iqbal

**Comment by abelnieva** [comment]
Hi @chipzoller , thank you for taking care of it . 

![image](https://user-images.githubusercontent.com/12033455/178547046-a7d2bc9c-b21a-4102-a16b-8a5b9191c6d2.png)

sorry i am still facing the same behavior

 `apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Rather than blocking Pods which come from outside registries,
      it is also possible to mutate them so the pulls are directed to
      approved registries. In some cases, those registries may function as
      pull-through proxies and can fetch the image if not cached.
      This policy policy mutates all images either
      in the form 'image:tag' or 'registry.corp.com/image:tag' to be 
      `XX.dkr.ecr.us-west-2.amazonaws.com/mirror/docker.io/`. Any path in the image name will be preserved.      
spec:
  background: false
  rules:
    - name: replace-image-registry-pod-containers
      match:
        any:
        - resources:
            kinds:
            - Pod
            namespaces:
            - "cattle*"
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', 'XX.dkr.ecr.us-west-2.amazonaws.com/mirror/docker.io' )}}"
    - name: replace-image-registry-pod-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', 'XX.dkr.ecr.us-west-2.amazonaws.com/mirror/docker.io' )}}"`

**Comment by chipzoller** [comment]
Ok, I see what's going on. Kyverno is reapplying to bare Pods in addition to the controller.

Try this which only applies to the Deployment and not to the Pods emitted from it. This can be adjusted to add more controllers that use the same schema, but you'll have to create additional rules for Jobs and CronJobs if you want those mutated.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-image-registry
  annotations:
    policies.kyverno.io/title: Replace Image Registry
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.7.1
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      Rather than blocking Pods which come from outside registries,
      it is also possible to mutate them so the pulls are directed to
      approved registries. In some cases, those registries may function as
      pull-through proxies and can fetch the image if not cached.
      This policy policy mutates all images either
      in the form 'image:tag' or 'registry.corp.com/image:tag' to be 
      `myregistry.corp.com/`. Any path in the image name will be preserved.      
spec:
  background: false
  rules:
    - name: replace-image-registry-pod-containers
      match:
        any:
        - resources:
            kinds:
            - Deployment
      mutate:
        foreach:
        - list: "request.object.spec.template.spec.containers"
          patchStrategicMerge:
            spec:
              template:
                spec:
                  containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', '4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io' )}}"
    - name: replace-image-registry-pod-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Deployment
      preconditions:
        all:
        - key: "{{ request.object.spec.template.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
            template:
              spec:
                initContainers:
                - name: "{{ element.name }}"
                  image: "{{ regex_replace_all_literal('^[^/]+', '{{element.image}}', '4742XXX03.dkr.ecr.us-west-1.amazonaws.com/mirror/docker.io' )}}"
```

I'll figure out how to best address this in the library.

**Comment by abelnieva** [comment]
@chipzoller thanks, I will test it out ,  in the being time this regex update works "{{ regex_replace_all_literal('.*docker.io\/', '{{element.image}}', 'XX.dkr.ecr.us-west-2.amazonaws.com/mirror/docker.io/' )}}"
